### ISSUE TITLE
getTopImage returns null

### ISSUE THREAD

**Issue by guybashan** [srijiths/readabilityBUNDLE#1]
I seems like there is a bug in the getTopImage.

When I try it, I get always "null".
Looking on the code, also shows that there is not assignment for "setTopImage" in case at least one candidate image is found.

**Comment by srijiths** [comment]
Hi Bashan ,

Its very long back i worked on this project. Let me have a look in to the project and get back to you.

Thanks,

**Comment by guybashan** [comment]
Hi srijiths,

It seems like the fix is working good.
Thanks for the fix and for the great project. :)

**Comment by srijiths** [comment]
Thank you Bashan,

Shoot more issues as i its very long since i optimized this project.
