### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jwilljacob** [srijiths/readabilityBUNDLE#2]
[ERROR] Failed to execute goal on project readabilityBUNDLE: Could not resolve dependencies for project com.sree.textbytes:readabilityBUNDLE:jar:0.0.1: The following artifacts could not be resolved: com.sree.textbytes:StringHelpers:jar:0.0.1, com.sree.textbytes:Network:jar:0.0.1: Could not find artifact com.sree.textbytes:StringHelpers:jar:0.0.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by srijiths** [comment]
@jwilljacob StringHelpers is not added in to maven central. You have to clone and build StringHelpers,Network and NextPageFinder in to your local. Then this issue will go off.

https://github.com/srijiths/Web-Pagination-Finder
https://github.com/srijiths/Network
https://github.com/srijiths/StringHelpers

In readabilityBundle Readme , you can see the Dependency Projects.

**Comment by srijiths** [comment]
@jwilljacob does it works ? If so , please close the issue.
