### ISSUE TITLE
Maven issues

### ISSUE THREAD

**Issue by ALEXFUNGZH** [srijiths/readabilityBUNDLE#3]
The eclipse ide tell me these:
   Missing artifact com.sree.textbytes:StringHelpers:jar:0.0.1
   Missing artifact com.sree.textbytes:Network:jar:0.0.1

Could u please help me?

**Comment by srijiths** [comment]
Both are separate projects that are not deployed in maven.  So you can find
both projects in my repos and import to your workspace.

Thanks

**Comment by ALEXFUNGZH** [comment]
Great！Thanks！
By the way，what is the different with readability and your code？
website：https://www.readability.com/
And what about support chinese website with your code？Have test?

**Comment by srijiths** [comment]
I have mentioned that in read me.  Please read. Since i am not relying much
on language, chinese mighy work.  Please check and let me know

**Comment by ALEXFUNGZH** [comment]
It's seems that not works good.
The content is null.
But anyway,thank you very much.

**Comment by srijiths** [comment]
Thanks. Closing this issue.
